"""Draft a revert PR on GitHub for a confirmed-bad commit.

This module is intentionally optional: the bisect tool works fine without it,
and most users will start in dry-run mode. When ready, set GITHUB_TOKEN
(scope: repo) and pass --open-pr to push a revert branch and open a PR.
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass
from typing import Optional


@dataclass
class RevertPR:
    title: str
    body: str
    branch: str
    base: str
    url: Optional[str] = None  # populated after the PR is opened


class GitHubError(RuntimeError):
    pass


def _short(sha: str) -> str:
    return sha[:8]


def build_revert_pr(
    bad_sha: str,
    base_branch: str,
    bisect_log: list[tuple[str, bool]],
    failing_test: str,
    stack_trace: str = "",
    short_subject: str = "",
) -> RevertPR:
    """Construct the metadata for a revert PR. Pure function — no network."""
    log_lines = "\n".join(f"- `{_short(sha)}` → {'pass' if ok else 'fail'}" for sha, ok in bisect_log)
    trace_block = ""
    if stack_trace:
        trimmed = stack_trace.strip()[:2000]
        trace_block = f"\n\n### Failing output\n\n```\n{trimmed}\n```\n"

    subject = short_subject or _short(bad_sha)
    title = f"Revert \"{subject}\" — auto-detected regression"
    body = (
        "## Auto-revert by Stack Trace Time Machine\n\n"
        f"Bisect identified `{bad_sha}` as the first commit where `{failing_test}` "
        "starts failing.\n\n"
        "### Bisect log\n\n"
        f"{log_lines}\n"
        f"{trace_block}\n"
        "_Generated by stt — review the diff before merging._\n"
    )
    return RevertPR(
        title=title,
        body=body,
        branch=f"stt/revert-{_short(bad_sha)}",
        base=base_branch,
    )


def open_revert_pr(
    repo_path: str,
    pr: RevertPR,
    bad_sha: str,
    remote: str = "origin",
    token: Optional[str] = None,
) -> RevertPR:
    """Cut a revert branch, push it, and open a PR via the gh CLI.

    We shell out to `gh` rather than implement the GitHub REST dance ourselves
    — gh handles auth, repo discovery, and PR creation correctly across both
    fork and non-fork setups, and most engineering machines already have it.
    """
    token = token or os.environ.get("GITHUB_TOKEN")
    if token is None:
        raise GitHubError("GITHUB_TOKEN not set; cannot open PR.")

    _run_git(repo_path, ["checkout", "-B", pr.branch, pr.base])
    _run_git(repo_path, ["revert", "--no-edit", bad_sha])
    _run_git(repo_path, ["push", "-u", remote, pr.branch])

    env = os.environ.copy()
    env["GH_TOKEN"] = token
    proc = subprocess.run(
        [
            "gh", "pr", "create",
            "--base", pr.base,
            "--head", pr.branch,
            "--title", pr.title,
            "--body", pr.body,
            "--draft",
        ],
        cwd=repo_path,
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )
    if proc.returncode != 0:
        raise GitHubError(f"gh pr create failed: {proc.stderr.strip()}")

    pr.url = (proc.stdout or "").strip().splitlines()[-1] if proc.stdout else None
    return pr


def _run_git(repo: str, args: list[str]) -> None:
    proc = subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        raise GitHubError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
